NHSDigital/shared-flow-testing

- azure/azure-pr-pipeline.yml
- tests/api_tests.py
> AMB-577 Run smoke test on deployments

- Makefile
- azure/templates/run-integration-tests.yml
- azure/templates/run-smoke-tests.yml
- proxies/live/apiproxy/proxies/default.xml
- tests/configuration/config.py
- tests/configuration/environment.py
- tests/test_endpoints.py
> AMB-577 Add 200 ok response to user-role-service endpoint

- proxies/live/apiproxy/proxies/default.xml
> Amb 577 migrate tests from mock proxy

- tests/test_endpoints.py
> AMB-612 add test for no role id on id token

- tests/requirements.txt
bump test-utils to last version
> AMB-000-bump-up-test-utils

- tests/configuration/environment.py
> AMB-751 add default value to SERVICE_BASE_PATH

- azure/azure-pr-pipeline.yml
- azure/templates/run-integration-tests.yml
> AMB-804 pass client_id from ssm

- azure/azure-release-pipeline.yml
> AMB-804 add client_id to release piplien

- proxies/live/apiproxy/policies/FlowCallout.ExtendedAttributes.xml
- proxies/live/apiproxy/proxies/default.xml
- tests/test_extended_attributes.py
Added the new ExtendedAttributes Flow callout with corresponding python tests.
> Added ExtendedAttributes flow callout and corresponding tests

- tests/conftest.py
- tests/test_endpoints.py
> APM-2861 Add cis2 token exchange tests

- tests/test_splunk_logging.py
> update splunk logging tests

- tests/test_splunk_logging.py
- tests/utils/splunk_logging_schema.json
> APM-4118 Test for headers being logged as object

- proxies/live/apiproxy/policies/AssignMessage.Swap.RequestHeaders.xml
- tests/test_splunk_logging.py
> APM-2550 test casing on header keys

- poetry.lock
- pyproject.toml
> APM-4135. Updated the version in pyproject.toml and synced the lockfile.

- pyproject.toml
> APM-4153 Update homepage url

- tests/test_enhanced_verify_api_key.py
> APM-5258 Change status code for enhanced verify apikey

- .gitignore
- Makefile
- proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml
- tests/test_splunk_logging.py
> Apm 4693 splunk logging

- tests/test_user_role_service_v2.py
- tests/test_user_roles.py
> APM-5594 unblock internal_ptl release pipeline

- sandbox/package-lock.json
- sandbox/package.json
> APM-6125: Resolve sandbox dependabot issues

- package-lock.json
- package.json
> APM-6125: Resolve dependabot alerts

- poetry.lock
- pyproject.toml
> APM-6125: Update black dependency
